import { writeFile } from "node:fs/promises";
import { generateColorTheme } from "@okramp/core";
import { createTDesignCss } from "@okramp/tdesign";

// Keep the logo's mint hue; derive readable UI colors for both appearances.
// Guide: https://okramp.seeridia.top/?page=guide&guideDoc=integrations/tdesign
const brandSeed = "#20C897";
// Shared by light and dark themes; keep circular and pill shapes unchanged.
const radii = {
  small: "4px",
  default: "8px",
  medium: "12px",
  large: "16px",
  extraLarge: "20px",
};
const radiusCss = `:root, :root[theme-mode="light"], :root[theme-mode="dark"] {
${Object.entries(radii)
  .map(([name, value]) => `  --td-radius-${name}: ${value};`)
  .join("\n")}
}`;
const theme = generateColorTheme(brandSeed, {
  mode: "both",
  // Structural surfaces, borders and text stay achromatic in both modes.
  // Reserve the seed hue for brand actions and selected states.
  neutral: { tintStrength: 0 },
  contrastPolicy: "adjust",
});

if (theme.diagnostics.contrastChecks.some((check) => !check.passes)) {
  throw new Error("The generated theme does not meet its contrast targets.");
}

await writeFile(
  new URL("../src/theme.css", import.meta.url),
  `/* Generated by npm run theme:generate. Edit scripts/generate-theme.mjs. */\n${createTDesignCss(theme)}\n\n${radiusCss}\n`,
);
